version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "air -c .air.toml"
    ports: 
      - 8080:8080
    tty: true
    volumes:
      - .:/usr/src/app

